const mongoose = require("mongoose");
const { Schema } = mongoose;
const RequestSchema = new Schema(
  {
    // id is auto generated by the DB
    url: {
      scheme: String,
      host: String,
      path: String,
    },
    response: {
      status: Number,
      statusText: String,
      date: String,
      server: String,
    },
    request: {
      method: String,
      http: String,
      url: String,
    },
  },
  { timestamps: true }
);

const RequestModel = mongoose.model("Request", RequestSchema);

module.exports = RequestModel;
